### PR TITLE
Filter uploads by tag, site id, or file path

### LINKED ISSUE #177: Filter upload/download tests
filter the export command by a tag, folder, or site to limit tests returned

- [ ] filter uploads
- [x] filter downloads

### PR DESCRIPTION
**Pull request by epaulet**
fixes #177

### CODE REVIEW

**Comment by ukd1** [comment]
@epaulet status?

**Comment by epaulet** [comment]
Finishing this up now.

**Comment by epaulet** [comment]
also fixes #170

**Comment by curtis-rainforestqa** [comment]
lgtm, i'm a 👍 with green build

**Pull request merged**
