### PR TITLE
get token from environment variable

### PR DESCRIPTION
**Pull request by valeriangalliat**
Rainforest token, if not given with `--token`, is fetched from the `RAINFOREST_API_TOKEN` environment variable.

### CODE REVIEW

**Comment by epaulet** [comment]
:+1: 

Please add a quick spec and fix merge conflicts and this should be good to go :)

**Comment by valeriangalliat** [comment]
Thnaks @epaulet, I updated the code with a spec.

**Comment by epaulet** [comment]
Looks like our circlemator gem is breaking builds from contributors without write access to this repo so I removed that gem in the master branch. Could you merge master into this branch? That way it should be green.

**Comment by valeriangalliat** [comment]
Done, test passed o/

**Pull request merged**
