### PR TITLE
RF-6455 Handle being given an empty string for the token

### PR DESCRIPTION
**Pull request by jbarber**
Previously the code would crash because it was attempting to look
out-of-bounds to do the comparison when handed an empty string for the
token.

### CODE REVIEW

**Comment by ukd1** [comment]
@jbarber I took a quick stab at fixing the tests for this, and confirmed it's still an issue in master 🤷🏻 

/reviewme @jbarber

**Comment by jbarber** [comment]
Looks good, I can't approve it because I'm the original author.

/reviewme @rainforestapp/devs

**Review by ukd1 — APPROVED** [review]

**Comment by ukd1** [comment]
@jbarber I approved

**Comment by ukd1** [comment]
@jbarber plz "LTGM" and I'll ship tomorrow.

**Comment by jbarber** [comment]
:shipit:

**Pull request merged**
