### PR TITLE
[DNM] Go Refactor [ETA: TBD]

### PR DESCRIPTION
**Pull request by macocha**
This is main PR for the go refactor.
More details: https://paper.dropbox.com/doc/Product-Narrative-Rainforest-cli-go-version-nsU4nrv5LciPqfIzNkuVk

TODOs:
- [x] Kill or document flag aliases
- [x] Fetch more than 100 resources
- [ ] Retry on HTTP request errors rather than exiting immediately
- [x] add tests for `startRun`
- [x] Add tests for rfml reader, validation & rm

### CODE REVIEW

**Comment by epaulet** [comment]
TODOs left over from last PR:

- [ ] Kill or document flag aliases
- [ ] Fetch more than 100 resources

@macocha

**Comment by epaulet** [comment]
Also - it might make sense to separate all the flags in a separate file since a lot of them are reused and `main()` is very full. Though I'm not married to the idea.

**Comment by epaulet** [comment]
I don't believe that the current Rainforest client does not try on 300+ statuses or timeouts. We should do that before we ship.

**Comment by juliankrispel** [comment]
GO REFACTOR!

**Comment by juliankrispel** [comment]
@epaulet @macocha what's the status? The expectation was that the refactor is done by end of last week and that we can test this week, is this still accurate?

**Comment by epaulet** [comment]
@juliankrispel the code is done, I'm gluing together pieces and testing it out and adding more unit tests.

**Comment by epaulet** [comment]
Gonna merge this branch into develop instead to make sure we have everything there.

**Pull request closed without merging**
