### PR TITLE
preserve tests' draft state when downloading RFML

### LINKED ISSUE #389: loss of state information when downloading tests in draft state
As late as `Rainforest CLI version 2.15.3 - stable channel - build: 12ce4c80`, `rainforest download` does not write
```
# state: draft
```
when it writes RFML for a test in `draft` state downloaded from the server. 

This means a user could `rainforest download` a test in `draft` state, make an arbitrary change, and `rainforest upload` the test. The test's state will change from state `draft` to state `enabled` on the server, which depending on whether the user is aware of this behavior and the user *wanted* the test to become `enabled`, is unexpected and undesired behavior.

Steps to reproduce:
1. Identify a test in draft state on the server and browse to it. Example browser URL is `https://app.rainforestqa.com/tests/XXXXXX/steps`
1. `rainforest download XXXXXX`
1. Note the written file name printed.
1. Note that file does not contain `# state: draft`.
1. `rainforest upload <file>`. `<file>` comes from step 3 above.
1. Observe the test's state on the server change from `draft` to `enabled`.

### PR DESCRIPTION
**Pull request by mikesbrown**
Fixes #389 

This seemed straightforward enough that I could submit a PR to fix, should you desire it. I've written a few tests to ensure desired behavior. Note that this should:

- Preserve behavior in which `enabled` state is not explicitly written with `rainforest download`
- Preserve behavior in which `rainforest new` does not write out any state
- Write out any new state added to the system in the future

### CODE REVIEW

**Comment by roman-dowakin** [comment]
Hi, Michael!

Thank you so much for PR!
I've tested functional of PR, it works perfectly. @magni- Could you please review code?

**Comment by roman-dowakin** [comment]
The functional changes were merged to master https://github.com/rainforestapp/rainforest-cli/pull/391 (We'll update dependencies in another PR).

We'll release new version in a few days! Thank you again for contributing!

**Comment by magni-** [comment]
On second thought, no need to wait to release :)

@mikesbrown Thanks for your contribution! I've just released your changes as `v2.17.0`. Unless you are using the `--skip-update` flag, your CLI should auto-update the next time you run it.

**Pull request closed without merging**
